services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandwich_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - sandwich-net

  postgres:
    image: postgres:15
    container_name: sandwich_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: sandwich
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sandwich-net

  redis:
    image: redis:7
    container_name: sandwich_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - sandwich-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: sandwich_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sandwich.com
      PGADMIN_DEFAULT_PASSWORD: sandwich
    networks:
      - sandwich-net

  nginx:
    image: nginx:alpine
    container_name: sandwich_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - sandwich-net

volumes:
  pgdata:

networks:
  sandwich-net:
    external: true
