services:
  postgres:
    image: postgres:15
    container_name: sandwich_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sandwich
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sandwich-net

  redis:
    image: redis:7
    container_name: sandwich_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - sandwich-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: sandwich_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sandwich.com
      PGADMIN_DEFAULT_PASSWORD: sandwich
    networks:
      - sandwich-net

volumes:
  pgdata:

networks:
  sandwich-net:
    external: true
