services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sandwich_app
    ports:
      - "8080:8080"
    restart: always         #재시작 정책 설정
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://sandwich_postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SANDWICH_USER_AWS_ACCESS_KEY_ID: ${SANDWICH_USER_AWS_ACCESS_KEY_ID}
      SANDWICH_USER_AWS_SECRET_ACCESS_KEY: ${SANDWICH_USER_AWS_SECRET_ACCESS_KEY}
    networks:
      - sandwich-net

  postgres:
    image: postgres:15
    container_name: sandwich_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_DB: sandwich
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c log_min_duration_statement=500
      -c log_statement=none
    networks:
      - sandwich-net

  redis:
    image: redis:7
    container_name: sandwich_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - sandwich-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: sandwich_pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sandwich.com
      PGADMIN_DEFAULT_PASSWORD: sandwich
    networks:
      - sandwich-net

  nginx:
    image: nginx:alpine
    container_name: sandwich_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../front/build:/app
      - ./public:/app/public   # 사용자 프로젝트 정적파일 저장소 들어갈 곳
    depends_on:
      - app
    networks:
      - sandwich-net

volumes:
  pgdata:

networks:
  sandwich-net:
    external: true
