services:
  postgres:
    image: postgres:15
    container_name: sandwich_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sandwich
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sandwich_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
