FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
WORKDIR /app
COPY requirements.txt .
RUN python -m pip install -U pip && pip install -r requirements.txt
COPY . .
EXPOSE 8010
CMD ["python","-m","uvicorn","src.api_redis.main:app","--host","0.0.0.0","--port","8010"]
